### ISSUE TITLE
Please describe a few of those commonalities

### ISSUE THREAD

**Issue by adlai** [Hexstream/common-lisp-format-reference#1]
I strongly discourage you from attempting to directly enumerate [these various commonalities](https://github.com/Hexstream/common-lisp-format-reference/blob/277cc8940e5aa4d2c9047a4c356d767e30402cf3/cross-reference/index.html#L50-L57), and ask that _you_ [and that pronoun refers to the reader, not necessarily to the author!] simply read the issue's name, although I have provided ignorable boilerplate content to thoroughly anchor the hyperlink into the published document.

**Comment by Hexstream** [comment]
I think your "these various commonalities" link points to the wrong place?

**edit:** Seriously, I might never have seen a more confusing issue than this...

**Comment by adlai** [comment]
> I think your "these various commonalities" link points to the wrong place?

Indeed it did, and I've corrected it.

> **edit:** Seriously, I might never have seen a more confusing issue than this...

The purpose of this issue is to provide a place for folks to collaboratively discuss the correct way to cross-reference between the format directives, preferably one slightly more organized than a chatroom... and yes, the task is a confusing one!

**Comment by Hexstream** [comment]
Ok. That would be fine to do, but [lispy-format 1.0](https://roadmap.hexstreamsoft.com/#lispy-format-1.0) will largely obsolete that.

**Comment by adlai** [comment]
> [...] [lispy-format 1.0](https://roadmap.hexstreamsoft.com/#lispy-format-1.0) will largely obsolete that.

Have you begun planning your library's structure? Ideally, if it is implemented on top of `CL:FORMAT` and its compilation-friendly sibling, then the HTML cross-reference should be generated from a datastructure that might be quite similar to one used by your library.

**Comment by Hexstream** [comment]
I'm not sure I'll be very motivated to properly document `format` once [lispy-format 1.0](https://roadmap.hexstreamsoft.com/#lispy-format-1.0) is out, but I do intend to properly document lispy-format 1.0 anyway, and it's not really clear to me what the value of using or documenting `format` would be at that time. I intend lispy-format 1.0 to completely obsolete `format`, to "relegate it to COBOL status", as I like to say. My intent is that `format` would only ever be used in legacy code from that point forward.

[I'm hoping to publish lispy-format 1.0 within the next 6 months.](https://www.hexstreamsoft.com/#5_january_2021)
It should be easier to know what to do with this issue at that time.

**Comment by adlai** [comment]
> [I'm hoping to publish lispy-format 1.0 within the next 6 months.](https://www.hexstreamsoft.com/#5_january_2021)
> It should be easier to know what to do with this issue at that time.

I have closed this issue to remove several false impressions: most notably, that there is a problem with the current published reference material, tracked in this repository; and also, that I expect anything specific of you in regards to further documentation of the existing format facility.

**Comment by Hexstream** [comment]
Don't be so hard on yourself...

My reference *is* incomplete, which is technically a problem with it. It's just that I have much higher priorities than fixing it, especially in the face of its probable imminent obsoletion.

Thank you for your interest in my work.

**Comment by adlai** [comment]
> Thank you for your interest in my work.

I find your motivation inspirational, and am glad that you are working on making Common Lisp an option competitive with the various rapid-moving new language frameworks. I am still more interested in improving my mastery of the implementations of the existing standard, and a few of the common libraries, although I agree with you that the format facility is cumbersome, and I hope to have few additions to this repository in the future once I have taken time to review it in detail.

**Comment by Hexstream** [comment]
Awesome! Thank you for the kind words.
